1:"$Sreact.fragment"
2:I[7555,[],""]
3:I[1295,[],""]
6:I[9665,[],"OutletBoundary"]
9:I[9665,[],"ViewportBoundary"]
b:I[9665,[],"MetadataBoundary"]
d:I[6614,[],""]
:HL["https://insertafter.com/_next/static/css/d8edca5e7193033b.css","style"]
:HL["https://insertafter.com/_next/static/css/93f5b1caf23b2daf.css","style"]
:HL["https://insertafter.com/_next/static/css/2b26a2222cb58ac3.css","style"]
0:{"P":null,"b":"2byf_F3pfdCEJ5l9bUm8H","p":"https://insertafter.com","c":["","articles-erreurs_javascript"],"i":false,"f":[[["",{"children":["(withRedirects)",{"children":[["locale","articles-erreurs_javascript","d"],{"children":["__PAGE__",{}]},"$undefined","$undefined",true]}]}],["",["$","$1","c",{"children":[null,["$","$L2",null,{"parallelRouterKey":"children","error":"$undefined","errorStyles":"$undefined","errorScripts":"$undefined","template":["$","$L3",null,{}],"templateStyles":"$undefined","templateScripts":"$undefined","notFound":[[["$","title",null,{"children":"404: This page could not be found."}],["$","div",null,{"style":{"fontFamily":"system-ui,\"Segoe UI\",Roboto,Helvetica,Arial,sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\"","height":"100vh","textAlign":"center","display":"flex","flexDirection":"column","alignItems":"center","justifyContent":"center"},"children":["$","div",null,{"children":[["$","style",null,{"dangerouslySetInnerHTML":{"__html":"body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}"}}],["$","h1",null,{"className":"next-error-h1","style":{"display":"inline-block","margin":"0 20px 0 0","padding":"0 23px 0 0","fontSize":24,"fontWeight":500,"verticalAlign":"top","lineHeight":"49px"},"children":404}],["$","div",null,{"style":{"display":"inline-block"},"children":["$","h2",null,{"style":{"fontSize":14,"fontWeight":400,"lineHeight":"49px","margin":0},"children":"This page could not be found."}]}]]}]}]],[]],"forbidden":"$undefined","unauthorized":"$undefined"}]]}],{"children":["(withRedirects)",["$","$1","c",{"children":[null,["$","$L2",null,{"parallelRouterKey":"children","error":"$undefined","errorStyles":"$undefined","errorScripts":"$undefined","template":["$","$L3",null,{}],"templateStyles":"$undefined","templateScripts":"$undefined","notFound":[[["$","title",null,{"children":"404: This page could not be found."}],["$","div",null,{"style":"$0:f:0:1:1:props:children:1:props:notFound:0:1:props:style","children":["$","div",null,{"children":[["$","style",null,{"dangerouslySetInnerHTML":{"__html":"body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}"}}],["$","h1",null,{"className":"next-error-h1","style":"$0:f:0:1:1:props:children:1:props:notFound:0:1:props:children:props:children:1:props:style","children":404}],["$","div",null,{"style":"$0:f:0:1:1:props:children:1:props:notFound:0:1:props:children:props:children:2:props:style","children":["$","h2",null,{"style":"$0:f:0:1:1:props:children:1:props:notFound:0:1:props:children:props:children:2:props:children:props:style","children":"This page could not be found."}]}]]}]}]],[]],"forbidden":"$undefined","unauthorized":"$undefined"}]]}],{"children":[["locale","articles-erreurs_javascript","d"],["$","$1","c",{"children":[[["$","link","0",{"rel":"stylesheet","href":"https://insertafter.com/_next/static/css/d8edca5e7193033b.css","precedence":"next","crossOrigin":"$undefined","nonce":"$undefined"}]],"$L4"]}],{"children":["__PAGE__",["$","$1","c",{"children":["$L5","$undefined",[["$","link","0",{"rel":"stylesheet","href":"https://insertafter.com/_next/static/css/93f5b1caf23b2daf.css","precedence":"next","crossOrigin":"$undefined","nonce":"$undefined"}],["$","link","1",{"rel":"stylesheet","href":"https://insertafter.com/_next/static/css/2b26a2222cb58ac3.css","precedence":"next","crossOrigin":"$undefined","nonce":"$undefined"}]],["$","$L6",null,{"children":["$L7","$L8",null]}]]}],{},null,false]},null,false]},null,false]},null,false],["$","$1","h",{"children":[null,["$","$1","uNCFA7sv0Kw-mHdUM7_G6",{"children":[["$","$L9",null,{"children":"$La"}],null]}],["$","$Lb",null,{"children":"$Lc"}]]}],false]],"m":"$undefined","G":["$d","$undefined"],"s":false,"S":true}
e:"$Sreact.strict_mode"
f:I[8873,["874","static/chunks/874-f855e4232fadb1a1.js","322","static/chunks/app/(withLocale)/%5Blocale%5D/layout-f7d50859cdd06b0e.js"],"default"]
10:I[2489,["874","static/chunks/874-f855e4232fadb1a1.js","322","static/chunks/app/(withLocale)/%5Blocale%5D/layout-f7d50859cdd06b0e.js"],"default"]
4:["$","$e",null,{"children":["$","html",null,{"lang":"articles-erreurs_javascript","children":["$","body",null,{"className":"layout_body__jFZuu","children":[null,["$","header",null,{"className":"header_iaHeader__4vCMA","children":["$","div",null,{"className":"$undefined","children":["$","h1",null,{"children":["$","a",null,{"href":"/articles-erreurs_javascript","title":"Go back to home page","className":"header_iaHeaderLogo__0uNr1","children":["$","img",null,{"src":"/images/logo.svg","alt":"InsertAfter's Logo"}]}]}]}]}],["$","$Lf",null,{"locale":"articles-erreurs_javascript","dictionary":{"home":{"label":"Home","title":"Go back to home page"},"blog":{"label":"Blog","title":"Read my blog posts"},"projects":{"label":"Projects","title":"Discover my projects"},"about":{"label":"About me","title":"Read more about me"}}}],["$","$L10",null,{"locale":"articles-erreurs_javascript"}],["$","main",null,{"className":"layout_iaMain__6s2gl","children":["$","div",null,{"children":["$","$L2",null,{"parallelRouterKey":"children","error":"$undefined","errorStyles":"$undefined","errorScripts":"$undefined","template":["$","$L3",null,{}],"templateStyles":"$undefined","templateScripts":"$undefined","notFound":"$undefined","forbidden":"$undefined","unauthorized":"$undefined"}]}]}],["$","aside",null,{"className":"social_iaSocial__kdR1x","children":["$","nav",null,{"children":["$","ul",null,{"children":[["$","li",null,{"children":["$","a",null,{"href":"https://mastodon.social/@nfroidure","rel":"me","title":"Follow me on Mastodon","className":"social_iaSocialMastodon__MTF6o","children":["$","span",null,{"children":"Mastodon"}]}]}],["$","li",null,{"children":["$","a",null,{"href":"https://bsky.app/profile/nfroidure.bsky.social","rel":"me","title":"Follow me on Bluesky","className":"social_iaSocialBluesky__fKW6M","children":["$","span",null,{"children":"Bluesky"}]}]}],["$","li",null,{"children":["$","a",null,{"href":"https://twitter.com/nfroidure","title":"Follow me on Twitter","className":"social_iaSocialTwitter__9nU6R","children":["$","span",null,{"children":"Twitter"}]}]}],["$","li",null,{"children":["$","a",null,{"href":"https://github.com/nfroidure","title":"See my GitHub projects","className":"social_iaSocialGithub__vcU5_","children":["$","span",null,{"children":"GitHub"}]}]}],["$","li",null,{"children":["$","a",null,{"href":"https://www.npmjs.org/~nfroidure","title":"Check my NPM modules","className":"social_iaSocialNpm__6nku5","children":["$","span",null,{"children":"NPM"}]}]}],["$","li",null,{"children":["$","a",null,{"href":"https://www.linkedin.com/in/nfroidure/","rel":"me","title":"See my LinkedIn profile","className":"social_iaSocialLinkedin__pWACO","children":["$","span",null,{"children":"LinkedIn"}]}]}],["$","li",null,{"children":["$","a",null,{"href":"https://facebook.com/nicolas.froidure.douai","rel":"me","title":"Follow me on Facebook","className":"social_iaSocialFacebook__w4wfH","children":["$","span",null,{"children":"Facebook"}]}]}],["$","li",null,{"children":["$","a",null,{"href":"/articles-erreurs_javascript/blog/index.atom","title":"Subscribe to my RSS feed","className":"social_iaSocialFeed__gEQQ0","children":["$","span",null,{"children":"RSS Feed"}]}]}]]}]}]}],["$","footer",null,{"className":"footer_iaFooter__rhlnQ","children":["$","p",null,{"className":"footer_iaFooterContent__VZndF","children":["© Nicolas Froidure 2012-",2025]}]}]]}]}]}]
a:[["$","meta","0",{"charSet":"utf-8"}],["$","meta","1",{"name":"viewport","content":"width=device-width, initial-scale=1"}],["$","meta","2",{"name":"theme-color","content":"#3e78b2"}]]
7:null
11:I[6874,["874","static/chunks/874-f855e4232fadb1a1.js","96","static/chunks/96-3883dbab65ddc99f.js","779","static/chunks/app/(withLocale)/%5Blocale%5D/%5B...slug%5D/page-f69cf0f70d06d9dc.js"],""]
5:[["$","section",null,{"className":"contentBlock_root__802UK","children":[[["$","h1","0",{"className":"h1_root__VPXQG","children":[["$","span","0",{"children":"Gestion des erreurs en JavaScript"}]]}],["$","p","1",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"Gérer les erreurs en JavaScript peut paraître simple, mais il n'est pas toujours évident de choisir entre exceptions, retours d'erreurs et callbacks d'erreurs."}]]}],["$","p","2",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"Le dernier Ch'tiJS a décidément été la source de nombreuses réflexions. L'une d'entre elle concernait les erreurs. Tout est parti d'une assertion simple : les promises doivent-elles attraper les exceptions et les transformer en erreurs récupérables dans un then ou les laisser remonter la pile d'exécution ?"}]]}],["$","p","3",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"C'est que fait, par exemple, RSVP.js. La logique du resolver est englobée dans "}],["$","$L11","1",{"href":"https://github.com/tildeio/rsvp.js/blob/277eb5eab912a9c3df8228a2647fcab84374615a/lib/rsvp/promise.js#L47","className":"a_root__WEPS7","title":"Voir le code en question","target":"_blank","children":[null,[["$","span","0",{"children":"un bloc try...catch"}]]]}],["$","span","2",{"children":" qui transforme toute exception en erreur qui fait échouer la promise. Dans "}],["$","$L11","3",{"href":"promises%5Fjavascript%5Fouvrons%5Fcapot.html","className":"a_root__WEPS7","title":"Voir l'article concernant cette implémentation","target":"_self","children":[null,[["$","span","0",{"children":"mon implémentation des promises"}]]]}],["$","span","4",{"children":", j'ai choisi de ne pas utiliser cette approche afin de pouvoir décider, au cas par cas, d'attraper ou non une exception envoyée par le resolver d'une promise."}]]}],["$","h2","4",{"className":"h2_root__Y02lX","children":["$","span",null,{"className":"anchored_root__HWi6K","children":[[["$","span","0",{"children":"Typologie des erreurs"}]]," ",["$","small",null,{"children":["$","$L11",null,{"href":"#typologie-des-erreurs","className":"anchored_icon__N5Sem","id":"typologie-des-erreurs","title":"Lien vers cette section","children":["$","span",null,{"children":"🔗"}]}]}]]}]}],["$","p","5",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"Avant d'aller plus loin, je voudrais revenir sur la typologie des erreurs que l'on peut rencontrer au cours de l'exécution d'un programme. Pour moi, il existe trois classes d'erreurs :"}]]}],["$","ul","6",{"className":"ul_ul__qh0e9","children":[["$","li","0",{"className":"li_root__oY9Dv","children":[["$","p","0",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"les erreurs fatales : ce sont des erreurs qui résultent d'une erreur de programmation. Ces dernières ont la particularité de ne pas avoir été prévues par le développeur puisqu'elles résultent d'un bug. Elles laissent donc le programme dans un état indéterminé. On pourrait comparer cette erreur aux erreurs HTTP 500+ ;"}]]}]]}],["$","li","1",{"className":"li_root__oY9Dv","children":[["$","p","0",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"les erreurs d'utilisation : elles sont causées par une mauvaise utilisation du programme (mauvaise saisies de l'utilisateur principalement) ;"}]]}]]}],["$","li","2",{"className":"li_root__oY9Dv","children":[["$","p","0",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"les erreurs d'interaction : un programme interagit fréquemment avec d'autres composants (le réseau, le matériel etc...). Il arrive qu'une interaction se termine de façon imprévue ou incohérente. Un programme se doit d'anticiper ces erreurs et de les gérer au mieux."}]]}]]}]]}],["$","p","7",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"Attention, certaines erreurs d'interaction peuvent être dues à une erreur fatale dans un programme avec lequel votre code interagit. C'est le cas quand une requête XHR renvoie une erreur 500. Il faut donc veiller à ne pas confondre erreurs d'interactions et erreurs fatales. Pour ce faire, il faut bien délimiter les erreurs qui sont dues à votre code."}]]}],["$","p","8",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"On pourrait considérer que les erreurs d'utilisation sont des erreurs d'interaction avec l'utilisateur. D'ailleurs, dans l'absolu, l'interaction avec des système tiers peut aussi induire des entrées qui nécessitent d'être filtrées de la même façon que les entrées utilisateur. Je fais néanmoins la différence ici car la réponse à ces erreurs sera légèrement différente."}]]}],["$","h2","9",{"className":"h2_root__Y02lX","children":["$","span",null,{"className":"anchored_root__HWi6K","children":[[["$","span","0",{"children":"La gestion d'erreur"}]]," ",["$","small",null,{"children":["$","$L11",null,{"href":"#la-gestion-d-erreur","className":"anchored_icon__N5Sem","id":"la-gestion-d-erreur","title":"Lien vers cette section","children":["$","span",null,{"children":"🔗"}]}]}]]}]}],["$","p","10",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"J'imagine que ces types vous évoquent certaines stratégies pour leur gestion. En JavaScript, on compte divers type de gestion d'erreur :"}]]}],["$","ul","11",{"className":"ul_ul__qh0e9","children":[["$","li","0",{"className":"li_root__oY9Dv","children":[["$","p","0",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"les exceptions : elles permettent à une erreur de remonter la pile d'exécution. On peut les attraper à tout moment à l'aide d'un bloc "}],["$","code","1",{"className":"code_root__5JLV_","children":"try...catch"}],["$","span","2",{"children":". Si elles ne sont pas attrapées, les exceptions finissent par interrompre l'execution de votre JavaScript (plus précisément de la pile d'exécution JavaScript)."}]]}]]}],["$","li","1",{"className":"li_root__oY9Dv","children":[["$","p","0",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"les retours d'erreur : il s'agit d'exploiter le retour de fonction pour indiquer qu'une erreur a eu lieu. On peut considérer que si "}],["$","code","1",{"className":"code_root__5JLV_","children":"parseInt"}],["$","span","2",{"children":" retourne "}],["$","code","3",{"className":"code_root__5JLV_","children":"NaN"}],["$","span","4",{"children":" alors on a affaire à une erreur. Cette approche est très utilisée en C pour les appels systèmes."}]]}]]}],["$","li","2",{"className":"li_root__oY9Dv","children":[["$","p","0",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"l'approche via une variable globale : très présente en C également avec la variable "}],["$","code","1",{"className":"code_root__5JLV_","children":"errno"}],["$","span","2",{"children":". En JavaScript, on évite les variables globales, on utilisera donc pas cette approche."}]]}]]}],["$","li","3",{"className":"li_root__oY9Dv","children":[["$","p","0",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"l'approche via callback d'erreur : ils sont principalement utilisés pour les opérations asynchrones, bien que rien n'empêche leur utilisation dans du code synchrone. C'est aussi l'approche qui est utilisée pour les promises. On passe un callback d'erreur à la méthode then. La différence est que l'on passe autant de callbacks d'erreur qu'on le souhaite."}]]}]]}]]}],["$","h2","12",{"className":"h2_root__Y02lX","children":["$","span",null,{"className":"anchored_root__HWi6K","children":[[["$","span","0",{"children":"Comment gérer chaque type d'erreur ?"}]]," ",["$","small",null,{"children":["$","$L11",null,{"href":"#comment-gerer-chaque-type-d-erreur","className":"anchored_icon__N5Sem","id":"comment-gerer-chaque-type-d-erreur","title":"Lien vers cette section","children":["$","span",null,{"children":"🔗"}]}]}]]}]}],["$","h3","13",{"className":"h3_root__kVaqq","children":["$","span",null,{"className":"anchored_root__HWi6K","children":[[["$","span","0",{"children":"Les erreurs fatales"}]]," ",["$","small",null,{"children":["$","$L11",null,{"href":"#les-erreurs-fatales","className":"anchored_icon__N5Sem","id":"les-erreurs-fatales","title":"Lien vers cette section","children":["$","span",null,{"children":"🔗"}]}]}]]}]}],["$","p","14",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"Les exceptions sont l'arme ultime pour gérer les erreurs fatales. En effet, puisque les erreurs fatales sont des erreurs de programmation, continuer l'exécution du programme est risqué. Cela pourrait avoir des répercussions désastreuses."}]]}],["$","p","15",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"JavaScript utilise intensivement les exceptions. Les erreurs de syntaxe, les mauvaises utilisations de son API native sont signalées dans la grande majorité des cas par des exceptions. C'est pourquoi je vous enjoins à fait de même."}]]}],["$","p","16",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"La plupart du temps, il s'agit de lever une exception si l'une de vos fonctions/l'un de vos constructeurs reçoit en paramètre des arguments erronés :"}]]}],["$","div","17",{"className":"code_root__5JLV_","children":["$","code",null,{"children":["$","pre",null,{"children":"function repeat(n) {\n  if (n < 0) throw new Error(\"Bad n value.\");\n  //...\n}"}]}]}],["$","p","18",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"Demander une répétition d'une opération avec une nombre négatif de répétition n'a pas de sens. Lancer une exception permet d'interrompre l'exécution et de permettre de déboguer facilement l'erreur dans le contexte où celle-ci est apparue."}]]}],["$","p","19",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"En effet, tous les outils pour développeurs permettent de placer un point d'arrêt à la levée d'une exception afin de permettre de visualiser les variables à portées, la pile d'exécution et bien d'autres informations très utiles."}]]}],["$","h3","20",{"className":"h3_root__kVaqq","children":["$","span",null,{"className":"anchored_root__HWi6K","children":[[["$","span","0",{"children":"Les erreurs d'utilisation"}]]," ",["$","small",null,{"children":["$","$L11",null,{"href":"#les-erreurs-d-utilisation","className":"anchored_icon__N5Sem","id":"les-erreurs-d-utilisation","title":"Lien vers cette section","children":["$","span",null,{"children":"🔗"}]}]}]]}]}],["$","p","21",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"Les erreurs d'utilisation sont dues à l'utilisateur. La logique veut donc que l'on traite ces erreurs en signalant celles-cis à l'utilisateur. C'est donc une réponse par le biais de l'interface utilisateur qui sera privilégiée."}]]}],["$","p","22",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"Cependant, pour activer cette réponse, il faut en premier lieu la détecter. Cette détection se fait indifféremment par retour de fonction ou par callback d'erreur. D'ailleurs il est très possible que vous deviez mixer ces deux techniques pour bâtir une propagation d'erreur dans la pile d'exécution et annuler certaines actions suite à une erreur."}]]}],["$","p","23",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"L'idée à retenir est d'éviter à tout prix de gérer les erreurs des utilisateurs à l'aide d'exceptions. En effet, vous prenez le risque de mettre fin à l'exécution pour une erreur normale dans le cycle de vie d'une application. Les utilisateurs se trompent souvent."}]]}],["$","p","24",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"On prendra donc soin de filtrer un entier obtenu grâce à une saisie de l'utilisateur avant de l'utiliser comme argument de la fonction "}],["$","code","1",{"className":"code_root__5JLV_","children":"repeat"}],["$","span","2",{"children":" définie ci-dessus."}]]}],["$","h3","25",{"className":"h3_root__kVaqq","children":["$","span",null,{"className":"anchored_root__HWi6K","children":[[["$","span","0",{"children":"Les erreurs d'interaction"}]]," ",["$","small",null,{"children":["$","$L11",null,{"href":"#les-erreurs-d-interaction","className":"anchored_icon__N5Sem","id":"les-erreurs-d-interaction","title":"Lien vers cette section","children":["$","span",null,{"children":"🔗"}]}]}]]}]}],["$","p","26",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"Lorsque votre code interagit avec des éléments extérieurs, qu'il s'agisse de serveurs distant ou du hardware, le bon sens veut que cela se fasse de manière asynchrone. Les callbacks d'erreur sont donc indiqués pour remplir le job. C'est d'ailleurs de cette façon que l'API JavaScript vous informe sur le succès ou l'échec d'une opération asynchrone."}]]}],["$","p","27",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"Ce n'est malheureusement pas toujours le cas. Par exemple, une requête XHR synchrone qui échoue à cause d'un problème réseau lance une exception. Dans ce cas précis, mieux vaut être au courant afin de placer le bloc "}],["$","code","1",{"className":"code_root__5JLV_","children":"try...catch"}],["$","span","2",{"children":" qui vous permettra de gérer ce cas sans mettre en péril l'exécution de votre JavaScript."}]]}],["$","p","28",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"Vous vous dîtes peut-être qu'il peut arriver qu'une erreur de programmation mène à la mauvaise utilisation d'une API asynchrone et que dans ce cas, un callback d'erreur sera appelé pour une erreur fatale. Ce que j'ai totalement contre indiqué tout à l'heure."}]]}],["$","p","29",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"Pour le cas d'une API bien pensée, cela ne devrait pas être le cas. Une API asynchrone doit détecter toute mauvaise utilisation et lancer une exception au moment de son lancement. Par exemple, si vous lancez une requête XHR vers une origine différente de votre site, c'est une erreur de programmation. Une exception doit être lancée immédiatement."}]]}],["$","p","30",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"L'astuce pour éviter tout effet de bord est de lancer l'opération asynchrone avant d'assigner les callbacks ou écouteurs d'évènements. De cette façon vous êtes certains que ces derniers ne seront jamais appelés en cas de levée d'une exception."}]]}],["$","h2","31",{"className":"h2_root__Y02lX","children":["$","span",null,{"className":"anchored_root__HWi6K","children":[[["$","span","0",{"children":"Retour sur les promises"}]]," ",["$","small",null,{"children":["$","$L11",null,{"href":"#retour-sur-les-promises","className":"anchored_icon__N5Sem","id":"retour-sur-les-promises","title":"Lien vers cette section","children":["$","span",null,{"children":"🔗"}]}]}]]}]}],["$","p","32",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"Avec cette toile de fond en tête, il apparaît donc évident que les exceptions ne doivent pas être attrapées au sein des promises. En effet, au delà de l'avantage d'une gestion au cas par cas, on voit aussi que cela pourrait compromettre la détection d'une erreur fatale causant la continuation de l'exécution à partir d'un état non-prévu donc indéterminé."}]]}],["$","p","33",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"On pourrait penser épargner l'utilisateur d'erreurs fatales qui en définitive mettent fin à l'exécution, mais au final, on rend les erreurs de programmation plus difficiles à détecter et les bugs plus sournois."}]]}],["$","p","34",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"Il faut comprendre que les erreurs fatales doivent être exceptionnelles. Un programme qui arrive en production doit être dénué d'erreurs fatales dans l'absolu. Malheureusement, dans le monde réel, ces erreurs peuvent survenir en production."}]]}],["$","p","35",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"Devons nous laisser les utilisateurs face à une application qui ne fonctionne plus ? Sûrement pas. L'approche correcte pour gérer les erreurs fatales est finalement assez simple. Il suffit d'utiliser un callback d'erreur générique, d'informer l'utilisateur d'une erreur anormale et de redémarrer l'application. On peut aussi imaginer récupérer ces erreurs fatales grâce à une requête XHR et de créer directement une issue sur GitHub. Un simple exemple :"}]]}],["$","div","36",{"className":"code_root__5JLV_","children":["$","code",null,{"children":["$","pre",null,{"children":"window.onerror = function (msg, url, line) {\n  //demande de détails\n  var details = prompt(\n    \"Une erreur fatale a eu lieu, vous pouvez donner quelques détails pour aider le webmaster :\",\n  );\n  // envoi des détails via XHR puis rafraîchissement de la page\n  document.location.refresh();\n};"}]}]}],["$","p","37",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"Ici, j'ai volontairement simplifié. Dans la pratique, on placera un timeout pour laisser le temps à toutes les erreurs consécutives d'être levées avant de demander du feedback et de redémarrer l'application. On peut aussi donner le temps à l'utilisateur de récupérer certains contenus (un formulaire à moitié rempli, par exemple) avant le rafraîchissement."}]]}],["$","p","38",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"L'avantage de cette approche est qu'on informe l'utilisateur d'un problème plutôt que vouloir le lui cacher quitte à ce que ce dernier provoque un effet papillon plus difficile à détecter."}]]}],["$","p","39",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"Voilà, j'espère que cet article vous a donné envie de gérer les erreurs de vos applications. Je vous propose de lire ce billet sur l'"}],["$","$L11","1",{"href":"bugmeback.html","className":"a_root__WEPS7","title":"Voir le billet sur BugMeBack","target":"_self","children":[null,[["$","span","0",{"children":"extension BugMeBack"}]]]}],["$","span","2",{"children":" qui propose une gestion intéressante des erreurs pour vos applications."}]]}],["$","p","40",{"className":"p_root__SHE_W","children":[["$","span","0",{"children":"Petit ajout : J'ai écrit "}],["$","$L11","1",{"href":"erreurs%5Fjavascript%5Fameliorees.html","className":"a_root__WEPS7","title":"Lire l'article","target":"_self","children":[null,[["$","span","0",{"children":"un autre article sur les erreurs en JS"}]]]}],["$","span","2",{"children":" mais cette fois avec des exemples concrets."}]]}]],["$","p",null,{"className":"p_root__SHE_W","children":["Published at"," ","mardi 30 juillet 2013 à 15:18:42","."]}]]}],["$","section",null,{"className":"contentBlock_root__802UK","children":["$","aside",null,{"className":"share_root__Qm_RR","children":[["$","h2",null,{"className":"h2_root__Y02lX","children":"Commenter et partager"}],["$","p",null,{"className":"p_root__SHE_W","children":[["$","$L11",null,{"href":"https://www.facebook.com/dialog/share?display=popup&href=https%3A%2F%2Finsertafter.com%2Fblog%2Ferreurs_javascript&redirect_uri=https%3A%2F%2Finsertafter.com","className":"a_root__WEPS7","title":"Commenter sur Facebook","target":"_blank","children":[null,[["$","span",null,{"className":"share_icon__bi4Q3 share_facebook__JKn8d"}],"Facebook"]]}]," - ",["$","$L11",null,{"href":"https://twitter.com/intent/tweet/?url=https%3A%2F%2Finsertafter.com%2Fblog%2Ferreurs_javascript&text=Gestion%20des%20erreurs%20en%20JavaScript&via=nfroidure","className":"a_root__WEPS7","title":"Commenter sur Twitter","target":"_blank","children":[null,[["$","span",null,{"className":"share_icon__bi4Q3 "}],"Twitter"]]}]," - ",["$","$L11",null,{"href":"mailto:nicolas.froidure@gmail.com","className":"a_root__WEPS7","title":"Me répondre par mail","target":"_self","children":[null,[["$","span",null,{"className":"share_icon__bi4Q3 share_mail__yvBDK"}],"Courriel"]]}]]}]]}]}],["$","section",null,{"className":"contentBlock_root__802UK","children":["$","aside",null,{"className":"page_linkedEntries__jiPuT","children":[["$","h2",null,{"className":"h2_root__Y02lX","children":"Articles similaires"}],["$","p",null,{"className":"p_root__SHE_W","children":["Dans les catégories"," ","JavaScript et Gestion des erreurs","."]}],["$","div",null,{"className":"items_entries__5hkLG","children":[["$","div","choisir_module_nodejs",{"className":"items_entry_item__GWeg7","children":[null,["$","h2",null,{"className":"h2_root__Y02lX items_entry_title__vJ_8h","children":["$","$L11",null,{"href":".//choisir_module_nodejs","className":"a_root__WEPS7 items_entry_link__EtVod","title":"Lire cet article de blog","target":"_self","children":[null,"Bien choisir ses modules NodeJS : ma méthode"]}]}],["$","p",null,{"className":"p_root__SHE_W items_entry_description__ZWt9y","children":["Hier à la troisième édition de ChtiJS, un question a été soulevée sur la confiance que l'on pouvait avoir dans les modules NodeJS. Je vous dévoile donc ma méthode pour trancher entre npm install et npm remove ;)."," ",["$","br",null,{}],["$","$L11",null,{"href":".//choisir_module_nodejs","className":"a_root__WEPS7","title":"Lire cet article de blog","target":"_self","children":[null,"Lire la suite"]}]]}],["$","p",null,{"className":"p_root__SHE_W items_entry_time__iNrot","children":["Published at"," ","vendredi 26 juillet 2013 à 16:04:25","."]}],["$","div",null,{"className":"items_clear__3fyGk"}]]}],["$","div","utiliser_requirejs",{"className":"items_entry_item__GWeg7","children":[null,["$","h2",null,{"className":"h2_root__Y02lX items_entry_title__vJ_8h","children":["$","$L11",null,{"href":".//utiliser_requirejs","className":"a_root__WEPS7 items_entry_link__EtVod","title":"Lire cet article de blog","target":"_self","children":[null,"Astuces pour utiliser pleinement RequireJS"]}]}],["$","p",null,{"className":"p_root__SHE_W items_entry_description__ZWt9y","children":["Pour un projet dont je vous reparlerai bientôt, j'ai utilisé RequireJS pour la première fois en production. J'en profite pour vous faire un petit retour d'expérience avec quelques astuces de mon cru ;)."," ",["$","br",null,{}],["$","$L11",null,{"href":".//utiliser_requirejs","className":"a_root__WEPS7","title":"Lire cet article de blog","target":"_self","children":[null,"Lire la suite"]}]]}],["$","p",null,{"className":"p_root__SHE_W items_entry_time__iNrot","children":["Published at"," ","jeudi 11 juillet 2013 à 11:57:45","."]}],["$","div",null,{"className":"items_clear__3fyGk"}]]}],["$","div","promises_javascript_ouvrons_capot",{"className":"items_entry_item__GWeg7","children":[null,["$","h2",null,{"className":"h2_root__Y02lX items_entry_title__vJ_8h","children":["$","$L11",null,{"href":".//promises_javascript_ouvrons_capot","className":"a_root__WEPS7 items_entry_link__EtVod","title":"Lire cet article de blog","target":"_self","children":[null,"Les promises avec JavaScript : ouvrons le capot !"]}]}],["$","p",null,{"className":"p_root__SHE_W items_entry_description__ZWt9y","children":["Dans le petit monde de JavaScript les promises font l'actualité. Je vous propose de comprendre les promises par l'implémentation."," ",["$","br",null,{}],["$","$L11",null,{"href":".//promises_javascript_ouvrons_capot","className":"a_root__WEPS7","title":"Lire cet article de blog","target":"_self","children":[null,"Lire la suite"]}]]}],["$","p",null,{"className":"p_root__SHE_W items_entry_time__iNrot","children":["Published at"," ","samedi 8 juin 2013 à 12:04:17","."]}],["$","div",null,{"className":"items_clear__3fyGk"}]]}]]}]]}]}]]
8:null
c:[["$","title","0",{"children":"Gestion des erreurs en JavaScript - Nicolas Froidure"}],["$","meta","1",{"name":"description","content":"Gérer les erreurs en JavaScript peut paraître simple, mais il n'est pas toujours évident de choisir entre exceptions, retours d'erreurs et callbacks d'erreurs."}],["$","link","2",{"rel":"author","href":"https://insertafter.com"}],["$","meta","3",{"name":"author","content":"Nicolas Froidure"}],["$","meta","4",{"name":"robots","content":"index, follow"}],["$","link","5",{"rel":"canonical","href":"https://insertafter.com/fr/blog/erreurs_javascript"}],["$","meta","6",{"property":"og:title","content":"Gestion des erreurs en JavaScript - Nicolas Froidure"}],["$","meta","7",{"property":"og:description","content":"Gérer les erreurs en JavaScript peut paraître simple, mais il n'est pas toujours évident de choisir entre exceptions, retours d'erreurs et callbacks d'erreurs."}],["$","meta","8",{"property":"og:url","content":"https://insertafter.com/fr/blog/erreurs_javascript"}],["$","meta","9",{"property":"og:site_name","content":"Nicolas Froidure"}],["$","meta","10",{"property":"og:locale","content":"fr_FR"}],["$","meta","11",{"property":"og:image:alt","content":"Bannière du site"}],["$","meta","12",{"property":"og:image","content":"https://insertafter.com/images/banner.png"}],["$","meta","13",{"property":"og:type","content":"article"}],["$","meta","14",{"name":"twitter:card","content":"summary"}],["$","meta","15",{"name":"twitter:site","content":"@nfroidure"}],["$","meta","16",{"name":"twitter:creator","content":"@nfroidure"}],["$","meta","17",{"name":"twitter:title","content":"Gestion des erreurs en JavaScript - Nicolas Froidure"}],["$","meta","18",{"name":"twitter:description","content":"Gérer les erreurs en JavaScript peut paraître simple, mais il n'est pas toujours évident de choisir entre exceptions, retours d'erreurs et callbacks d'erreurs."}],["$","meta","19",{"name":"twitter:image:alt","content":"Bannière du site"}],["$","meta","20",{"name":"twitter:image","content":"https://insertafter.com/images/banner.png"}],["$","link","21",{"rel":"icon","href":"/images/favicon.svg","type":"image/svg+xml","sizes":"any"}],["$","link","22",{"rel":"icon","href":"/images/favicon-16.png","type":"image/png","sizes":"16x16"}],["$","link","23",{"rel":"icon","href":"/images/favicon-128.png","type":"image/png","sizes":"128x128"}]]
